name: Tests and Comilation (disabled)

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
        TEST_RUN: false

    steps:
    - name: Checkout repozytorium
      uses: actions/checkout@v3

    - name: Install cppcheck dependency
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck

    - name: Run cppcheck
      run: cppcheck --enable=all --check-level=exhaustive --suppress=missingIncludeSystem --inconclusive filozofowie/main.cpp

    - name: Install comilation dependencies
      if: env.TEST_RUN == 'true'
      run: sudo apt-get install -y g++ make

    - name: Compile the program
      if: env.TEST_RUN == 'true'
      run: |
        cd filozofowie
        make


    - name: Run the program with argument (5 philosophers, for 120 seconds)
      if: env.TEST_RUN == 'true'
      run: |
        cd filozofowie
        ./filozofowie 5 120
